version: '3.6'

networks:
    default:
        driver: bridge

services:
    db:
        image: mysql:5.7
        user: "1000:1000"
        restart: "no"
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=$DB_NAME
            - MYSQL_USER=$DB_USER
            - MYSQL_PASSWORD=$DB_PASSWORD
        networks:
            - default
        ports:
            - 3306:3306
        volumes:
            - ./.db-data:/var/lib/mysql
            - ./etc/mysql.conf.d:/etc/mysql/conf.d
    node:
        build:
            context: .
            dockerfile: Dockerfile
        user: "1000:1000"
        restart: "no"
        env_file: .env
        environment:
            - DB_HOST=$DB_HOST
            - DB_PORT=$DB_PORT
            - DB_NAME=$DB_NAME
            - DB_USER=$DB_USER
            - DB_PASSWORD=$DB_PASSWORD
        links:
            - db
        networks:
            - default
        ports:
            - 8084:8084
        expose:
            - 8084
        volumes:
            - .:/usr/src/app/:rw
            - ./.cert:/usr/src/app/.cert:ro
